const lexicalTheme = {
  ltr: "text-left",
  rtl: "text-right",
  placeholder: "text-muted-foreground opacity-50",
  paragraph: "mb-2 last:mb-0",
  quote: "border-l-4 border-muted pl-4 my-2",
  heading: {
    h1: "text-3xl font-bold mb-4 dark:text-foreground",
    h2: "text-2xl font-semibold mb-3 dark:text-foreground",
    h3: "text-xl font-medium mb-2 dark:text-foreground",
    h4: "text-lg font-medium mb-2 dark:text-foreground",
    h5: "text-base font-medium mb-2 dark:text-foreground",
  },
  list: {
    checklist: 'relative',
    listitem: 'mx-2',
    listitemChecked: 'relative mx-2 px-6 list-none outline-none line-through listitemChecked',
    listitemUnchecked: 'relative mx-2 px-6 list-none outline-none listitemUnchecked',
    nested: {
      listitem: 'list-none before:hidden after:hidden',
    },
    olDepth: [
      'p-0 m-0 list-outside',
      'p-0 m-0 list-[upper-alpha] list-outside',
      'p-0 m-0 list-[lower-alpha] list-outside',
      'p-0 m-0 list-[upper-roman] list-outside',
      'p-0 m-0 list-[lower-roman] list-outside',
    ],
    ul: 'p-0 m-0 list-outside',
  },
  image: "max-w-full h-auto",
  link: "text-primary hover:underline dark:text-primary",
  text: {
    bold: "font-bold",
    italic: "italic",
    overflowed: "text-ellipsis overflow-hidden",
    hashtag: "text-primary dark:text-primary",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted text-muted-foreground rounded px-1 py-0.5 font-mono text-sm dark:bg-muted dark:text-muted-foreground",
  },
  code: "bg-muted text-muted-foreground rounded p-2 font-mono text-sm block whitespace-pre-wrap dark:bg-muted dark:text-muted-foreground",
  codeHighlight: {
    atrule: "text-primary dark:text-primary",
    attr: "text-primary dark:text-primary",
    boolean: "text-accent dark:text-accent",
    builtin: "text-accent-foreground dark:text-accent-foreground",
    cdata: "text-muted-foreground dark:text-muted-foreground",
    char: "text-accent-foreground dark:text-accent-foreground",
    class: "text-secondary dark:text-secondary",
    "class-name": "text-secondary dark:text-secondary",
    comment: "text-muted-foreground dark:text-muted-foreground",
    constant: "text-accent dark:text-accent",
    deleted: "text-destructive dark:text-destructive",
    doctype: "text-muted-foreground dark:text-muted-foreground",
    entity: "text-accent dark:text-accent",
    function: "text-secondary dark:text-secondary",
    important: "text-accent font-bold dark:text-accent",
    inserted: "text-success dark:text-success",
    keyword: "text-primary dark:text-primary",
    namespace: "text-accent dark:text-accent",
    number: "text-accent dark:text-accent",
    operator: "text-muted-foreground dark:text-muted-foreground",
    prolog: "text-muted-foreground dark:text-muted-foreground",
    property: "text-accent dark:text-accent",
    punctuation: "text-muted-foreground dark:text-muted-foreground",
    regex: "text-accent dark:text-accent",
    selector: "text-primary dark:text-primary",
    string: "text-success dark:text-success",
    symbol: "text-accent dark:text-accent",
    tag: "text-primary dark:text-primary",
    url: "text-accent underline dark:text-accent",
    variable: "text-destructive dark:text-destructive",
  },
};

export default lexicalTheme;